export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";

export const OPEN_PAY_MODAL = "OPEN_PAY_MODAL";
export const CLOSE_PAY_MODAL = "CLOSE_PAY_MODAL";
export const CLOSE_PAY_MODAL_BUTTON = "CLOSE_PAY_MODAL_BUTTON";

export const SHOW_PAY_MODAL = "SHOW_PAY_MODAL";
export const DONT_SHOW_PAY_MODAL = "DONT_SHOW_PAY_MODAL";

export const SHOW_BACKDROP = "SHOW_BACKDROP";
export const DONT_SHOW_BACKDROP = "DONT_SHOW_BACKDROP";
